// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZRgHucXWRTHBNYmVeOMMRSRuD7RffYU',
    appId: '1:813895188113:web:8eeec8f19022171a84c930',
    messagingSenderId: '813895188113',
    projectId: 'bellaskitchen-cefcb',
    authDomain: 'bellaskitchen-cefcb.firebaseapp.com',
    storageBucket: 'bellaskitchen-cefcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3B60-MPYMhXKw6rodfDBQn09hb0HKqo',
    appId: '1:813895188113:android:e72fca997730c4a184c930',
    messagingSenderId: '813895188113',
    projectId: 'bellaskitchen-cefcb',
    storageBucket: 'bellaskitchen-cefcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTbXrBwDw5q2Ad2i8cDBDDgwGi2E4WYM',
    appId: '1:813895188113:ios:c13be385efeb83d584c930',
    messagingSenderId: '813895188113',
    projectId: 'bellaskitchen-cefcb',
    storageBucket: 'bellaskitchen-cefcb.firebasestorage.app',
    iosBundleId: 'com.example.bellasKitchen',
  );
}
